### ISSUE TITLE
Brachytherapy Reference points

### ISSUE THREAD

**Issue by thothwang** [rexcardan/ESAPIX#11]
Dear Rex,

We're trying to get multiple reference points dose from Brachytherapy plan, with help of ESAPI.
However, we did not find these items in PlanSetup/Course/Patient class.
We only found "PrimaryReference Point" under planSetup, which is not sufficient.
Could you give a hint?
Thanks in advance.

**Comment by rexcardan** [comment]
Hello, thanks for your interest in ESAPI. However, this forum is for issues with the ESAPI extension library : ESAPIX. Please submit questions like this to the Varian GitHub [repo](https://github.com/VarianAPIs/samples).
