### ISSUE TITLE
ESAPIX_Bootstrapper _v15.6 appears to be missing from nuget.org

### ISSUE THREAD

**Issue by JJLucido** [rexcardan/ESAPIX#17]
Hi Rex,

I'm really excited that you have provided this tool, but am having a few issues: 

1) I am unable to find ESAPIX_Bootstrapper_V15.6 from nuget.org (I can find the bootstrapper for 15.5 and ESAPIX for all listed version). Is this intentional or is this somehow deprecated for 15.6?

2) In the "Bootstrapping Your Stand Alone App" documentation, there should be a class Bootstrapper.FacadeInitializer, which does not appear in the the code or downloaded packages. according to the documentation it is in the namespace ESAPIX_FacadeBuilder, which I also cannot find in the code or the packages, either. 

3) The documentation refers to "ESAPIX.Facade.Serialization.FacadeSerializer.SerializeSettings", but I cannot find an instance of this in either the open source code or the downloadable package. 

I'm willing to provide assistance with any help you need with these issues.

Thanks again for all the work!

John

**Comment by rexcardan** [comment]
ESAPIX.Bootstrapper is not needed anymore. I recommend using (cloning) https://github.com/rexcardan/ESAPIX_WPF_Example and start from there.
