### ISSUE TITLE
ESAPIX.Bootstrapper is missing  version 15.6  and Facade in source code

### ISSUE THREAD

**Issue by hrnourzadeh** [rexcardan/ESAPIX#19]
I tried to install ESAPIX.Bootstrapper for Eclipse V 15.6, but it seems to be missing from the NuGet package manager. So I tried to build the code. While ESAPIX builds with no issue ESAPIX.Bootstrapper project has a broken reference to ESAPIX.Facade.API.

**Comment by rexcardan** [comment]
ESAPIX.Bootstrapper is not needed anymore. I recommend using (cloning) https://github.com/rexcardan/ESAPIX_WPF_Example and start from there.
