### ISSUE TITLE
 MayoQueryReader not considering "MaxDose[Gy]" as valid query.

### ISSUE THREAD

**Issue by victorgabr** [rexcardan/ESAPIX#5]
Hi Rex,

MayoQueryReader.IsValid is not considering "MaxDose[Gy]", "MeanDose[Gy]" and "MinDose[Gy]" as valid. 
The regex pattern MayoRegex.Valid may not be right. 

Here there is a simple console program to check it.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Test_Regex
{

    public class MayoRegex
    {
        public const string UnitsDesired = @"\[(cc|%|(c?Gy))\]";
        public const string QueryType = @"^(V|CV|DC|D|Mean|Max|Min)";
        public const string QueryValue = @"\d+(\.?)(\d+)?";
        public const string QueryUnits = @"((cc)|%|(c?Gy))";
        public static string Valid = $"(((V|CV|DC|D)({QueryValue}{QueryUnits}))|(Mean|Max|Min)){UnitsDesired}";
    }

    class Program
    {
        static void Main(string[] args)
        {
            //Console.WriteLine(MayoRegex.UnitsDesired);
            //Console.WriteLine(MayoRegex.QueryType);
            //Console.WriteLine(MayoRegex.QueryValue);
            //Console.WriteLine(MayoRegex.QueryUnits);
            //Console.WriteLine(MayoRegex.Valid);

            string query_max = "MaxDose[Gy]";
            Console.WriteLine(IsValid(query_max).ToString());

            string query_mean = "MeanDose[Gy]";
            Console.WriteLine(IsValid(query_mean).ToString());

            string query_min = "MinDose[Gy]";
            Console.WriteLine(IsValid(query_min).ToString());

            Console.ReadLine();

        }

        // same function from MayoQueryReader
        public static bool IsValid(string query)
        {
            var isMatch = Regex.IsMatch(query, MayoRegex.Valid, RegexOptions.IgnoreCase);
            return isMatch;
        }
    }
}

Regards,
Victor

**Comment by rexcardan** [comment]
Mayo syntax is Max[Gy], Min[Gy] and Mean[Gy]

**Comment by victorgabr** [comment]
Got it.  
So, should you change this line?

var max = ps.ExecuteQuery(prostate, "MaxDose[Gy]");

I was trying these examples:

https://github.com/rexcardan/ESAPIX/blob/master/DocFX/articles/mayoFormat.md

Regards,

**Comment by victorgabr** [comment]
I've Just tested again "MaxDose[Gy]" is also considered. Maybe, clean and rebuild have solved everything. :) Better close this issue.  Thanks
