### ISSUE TITLE
What happened to "GenerateFacadeApp" ?

### ISSUE THREAD

**Issue by fizxmike** [rexcardan/ESAPIX#6]
Currently using ESAPI 13.7 and was trying to make use of the Async Await functionality enabled by ESAPIX following this video (specifically the "GetApp()" function in a VMSLink implementation):
https://youtu.be/0JDXpvOqXoc?t=5m51s

But "GenerateFacadeApp" seems to have been done away with in favor of "ESAPIX.AppKit.AppBootstrapper<W>(USERNAME, PASSWORD)" where W must be a Window...? Am I missing something?

... The trouble is I have already isolated and abstracted my VMS.TPS.Common.Application inside a ViewModel which is also a child of my main ViewModel... passing down a Window object just to get ESAPIX hooked up seems like I'd be mixing up concerns (like in MVVM they say my ViewModel shouldn't need to know anything about my View/Window). I'd much rather just initialize an ESAPIX Application down inside the child ViewModel and run unit tests directly on that ViewModel as well.

I'm sorry if I overlooked some key documentation, feel free to point me there. Thanks!

**Comment by rexcardan** [comment]
I have been thinking about this myself. I am thinking I will refactor WPF parts outside of my core ESAPIX and spin off a ESAPIX.WPF for that functionality. Its actually pretty simple to get the Facade magic working. Take a look at the AppBootstrapper constructor:

https://github.com/rexcardan/ESAPIX/blob/master/ESAPIX.Bootstrapper/AppBootstrapper.cs

0. Call ESAPIX.Bootrapper.FacadeInitializer.Initialize() to wire up VMS to ESAPIX

1. Create a facade application to wrap all calls to ESAPI. 

If you already have a VMS.App instance (called "app" for example) running, you can wrap it in a Facade:

`var facade = new ESAPIX.Facade.API.Application(app);`

2. You have to set the XContext singleton so all threads can know where the correct thread is. (This is done automatically in StandAloneContext.Create(vmsUsername, vmsPassword, singleThread)).

You can do:
`XContext.Instance.CurrentContext = new StandaloneContext(facade,null);`

ESAPIX is very opinionated about how WPF should be done. The view models from ESAPIX don't know  if you are in standalone mode or script mode. They simply use IScriptContext to pass an interface via dependency injection to your VM. Have you looked at my starter WPF template. It wires up everything for you.

Starter WPF is on the Visual Studio Marketplace (for free). Youtube video here (https://www.youtube.com/watch?v=qPVIR8Jxs94). Source code here (https://github.com/rexcardan/ESAPIX/tree/master/ESAPIX.StarterWPF/ESAPIX136).

Let me know if you can't get it working and I can help set up a sample for you.

**Comment by fizxmike** [comment]
Thanks for the examples! I'm working through it, but "ESAPIX.Facade.Types" is missing... was it renamed or do I need to keep a reference to VMS....Types instead?

**Comment by rexcardan** [comment]
ESAPIX.Facade.Types? Wow that must be some old code. You might want to pull the most recent source ESAPIX 13.6 and just swap dlls. I don't have 13.7 so I don't update as often. Let me know if you can't work through it and I will try to get a solution.

**Comment by fizxmike** [comment]
... also, quick, somewhat related, question: Do you auto generate the files in https://github.com/rexcardan/ESAPIX/tree/master/ESAPIX/Facade/API automatically or by hand? If automatically, is the script to do that in this repo?

**Comment by rexcardan** [comment]
I have it automated...but that is some secret sauce I haven't included in this repo. Maybe sometime in the future.
