### ISSUE TITLE
RTPrescription and RTPrescriptionTarget ESAPIX 13.6

### ISSUE THREAD

**Issue by Lukas-VanDyke** [rexcardan/ESAPIX#9]
I've noticed that RTPrescription and RTPrescriptionTarget are available in ESAPIX 15.5 but not in 13.6.

I was wondering if there were a particular reason for this or if they were going to be added at some point.
I created class files for them based on your other facade files, but haven't been able to test them because of a number of errors with the VMS dll's.

I haven't used github much so I wasn't sure how to go about creating a pull request for them, but they should be attached to this issue. 

Thanks

[RTPresciption.zip](https://github.com/rexcardan/ESAPIX/files/1890640/RTPresciption.zip)

**Comment by rexcardan** [comment]
ESAPIX just mimics the VMS...API dlls. I don't make those classes by hand. I built code generators which create those from the real dlls. If its missing, it should mean that the class is not available in the version 13.6 dlls provided by Varian. I looked just now and confirmed they are not present (at least in my copies). Are you able to access RTPrescription in ESAPI 13.6 (the standard one, not ESAPIX)? If so, can you show me example code, so I can replicate on my end?

**Comment by Lukas-VanDyke** [comment]
Yes, I can access RTPrescription is ESAPI 13.6.
Here's an example of how I was using it:

public static Dictionary<string, int> getPrescriptionFractionsEclipse(VMS.TPS.Common.Model.API.PlanSetup plan, out Exception e)
        {
            Dictionary<string, int> targetFractions = new Dictionary<string, int>();
            try
            {
                RTPrescription pres = plan.RTPrescription;
                foreach (RTPrescriptionTarget target in pres.Targets)
                {
                    targetFractions.Add(target.TargetId, target.NumberOfFractions);
                }
                e = null;
            }
            catch (Exception ex)
            {
                e = ex;
                targetFractions = null;
            }
            return targetFractions;
        }

Here's a picture of the ESAPI help documentation for the RTPrescription class:

![rtprescription](https://user-images.githubusercontent.com/2432662/38511974-154b278e-3be7-11e8-8b33-ce2abca87166.png)

**Comment by rexcardan** [comment]
I don't know what to tell you. In my version of 13.6 and 13.7, I don't have that option in my PlanSetup class:

![image](https://user-images.githubusercontent.com/2116960/38512978-76edf542-3bf2-11e8-9d52-84915339193c.png)

And here is the dll file I am compiling against:
![image](https://user-images.githubusercontent.com/2116960/38513098-ce557c06-3bf2-11e8-88a5-a06bf712af16.png)

**Comment by Lukas-VanDyke** [comment]
I'm compiling against a different version:
![vmsversion](https://user-images.githubusercontent.com/2432662/38513313-091c7392-3beb-11e8-9ee9-a6c486bde08a.png)

I'll try to create my own facade classes for RTPrescription and RTPrescriptionTarget.

Thanks anyways.
